name : Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron : 30 02 * * * # 8 am IST Everyday
    - cron : 00 14 * * * #7:30 PM IST Everyday
    - cron : 00 06 * * 1-5  #1130 am IST Monday to Friday
jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v6.0.2

      - name: Install Nodejs and npm
        uses: actions/setup-node@v6.3.0
        with:
          node-version: '22'
      - name: Install Newman and HTML-extra globally
        run: | 
             npm install -g newman
             npm install -g newman-reporter-htmlextra

      - name: Run the postman Collection with newman
        run: |
             newman run 'Inwarranty-flow Collection.postman_collection.json' \
             -e QA.postman_environment.json \
             -d testData.csv \
             -r cli,htmlextra \
             --reporter-htmlextra-export ./newman/index.html
             
        

      - name: Newman Report
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: newman-html-report
          path: newman/*.html

      - name: Creating github page branch
        if: always()
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: newman/

      - name: Send Email Notification
        if: always()
        uses: dawidd6/action-send-mail@d38f3f7cd391cdebfe0d38efc3998b935e951c4f
        with:
          server_address: smpt.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Phoenix Inwarranty Flow Test Execution Notification
          to: sanu27anand@gmail.com
          from: ${{ secrets.EMAIL_USERNAME }}
          body: | 
                Hi,
                Phoenix Inwarranty flow test has been executed. The report has been published and the URL
                is: https://sanu16.github.io/Phoenix-Inwarranty-Flow/
          
          
          
        
          
        
        
          
      
    
